import { StyleSheet } from "react-native";

export default StyleSheet.create({
	container: {
		flex: 1,
		alignItems: "center",
	},
	title: {},
	logo: {
		flex: 1,
		height: 300,
		width: 200,
		alignSelf: "center",
		margin: 10,
		resizeMode: 'contain',
	},
	alertContainer: {
		backgroundColor: "#6C60CC",
		marginLeft: 500,
		marginRight: 500,
		marginTop: 20,
		height: 48,
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center"
	},
	input: {
		height: 48,
		borderRadius: 5,
		overflow: "hidden",
		backgroundColor: "white",
		marginTop: 10,
		marginBottom: 10,
		marginLeft: 30,
		marginRight: 30,
		paddingLeft: 16,
	},
	button: {
		backgroundColor: "#6C60CC",
		marginLeft: 500,
		marginRight: 500,
		marginTop: 20,
		height: 48,
		borderRadius: 15,
		alignItems: "center",
		justifyContent: "center",
	},
	buttonText: {
		fontSize: 18,
		color: 'white',
		alignSelf: 'center',
	  },
	buttonTitle: {
		color: "white",
		fontSize: 16,
		fontWeight: "bold",
	},
	footerView: {
		flex: 1,
		alignItems: "center",
		marginTop: 150,
	},
	footerText: {
		fontSize: 16,
		alignItems: "flex-end",
		//marginTop: 50,
		fontFamily: "monospace",
		color: "#FFFFFF",
	},
	footerLink: {
		color: "#788eec",
		fontWeight: "bold",
		fontSize: 16,
	},
	notifySection:{
		display: "flex",
		flexDirection: "row",
		alignContent: "center",
		textAlign: "center",
		alignItems: "center",
		marginBottom: 20,
		marginTop: 50,
		backgroundColor: "white",
		borderRadius: 20,
		height: 90,
		padding: 20,
		shadowColor: "gray",
		shadowOffset: {
			width: 0,
			height: 7,
		},
		shadowOpacity: 1,
		shadowRadius: 4,
		elevation: 20,
	},
	
});
